In [ ]:
import torch
import numpy as np

from torchvision import transforms, datasets
import torchvision
import fiftyone.zoo as foz
import fiftyone as fo
from data_service import DataAugmentation

import random

from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as T
import torch.nn as nn
from torchvision.utils import make_grid
from torchvision.utils import save_image
from IPython.display import Image
import matplotlib.pyplot as plt
import numpy as np
import random

In [3]:
foz.list_zoo_datasets()

['bdd100k',
 'caltech101',
 'caltech256',
 'cifar10',
 'cifar100',
 'cityscapes',
 'coco-2014',
 'coco-2017',
 'fashion-mnist',
 'hmdb51',
 'imagenet-2012',
 'imagenet-sample',
 'kitti',
 'lfw',
 'mnist',
 'open-images-v6',
 'quickstart',
 'quickstart-geo',
 'quickstart-video',
 'ucf101',
 'voc-2007',
 'voc-2012']

In [5]:
# The directory containing the dataset to import
dataset_dir = "~/fiftyone/coco-2017/validation/"


# dataset = fo.Dataset.from_dir(
#     dataset_dir=dataset_dir,
#     dataset_type=fo.types.ImageSegmentationDirectory,
#     labels_path='labels.json',
# )

dataset = foz.load_zoo_dataset(
    "coco-2017",
    dataset_dir="coco-2017_50000",
    splits=["train", "test", "validation"],
    label_types=["segmentations"],
    max_samples=50000,
)

   1% ||-----|   21.0Mb/1.9Gb [1.3m elapsed, 2.1h remaining, 88.7Kb/s]    


KeyboardInterrupt: 

In [2]:
session = fo.launch_app(dataset)





coco_train = datasets.CocoDetection(root = data_path, annFile = labels_path)
  

Found annotations at '/home/sumbel/fiftyone/coco-2017/raw/instances_train2017.json'
 100% |████████████████████| 25/25 [3.7s elapsed, 0s remaining, 10.0 images/s]      
Writing annotations for 25 downloaded samples to '/home/sumbel/fiftyone/coco-2017/train/labels.json'
Test split is unlabeled; ignoring classes requirement
 100% |██████|    8.7Mb/8.7Mb [2.5s elapsed, 0s remaining, 4.4Mb/s]      
Extracting test info to '/home/sumbel/fiftyone/coco-2017/raw/image_info_test2017.json'
 100% |████████████████████| 25/25 [4.2s elapsed, 0s remaining, 6.2 images/s]       
Writing annotations for 25 downloaded samples to '/home/sumbel/fiftyone/coco-2017/test/labels.json'
Found annotations at '/home/sumbel/fiftyone/coco-2017/raw/instances_val2017.json'
Sufficient images already downloaded
Existing download of split 'validation' is sufficient
Loading 'coco-2017' split 'train'
 100% |███████████████████| 25/25 [203.9ms elapsed, 0s remaining, 123.3 samples/s]    
Loading 'coco-2017' split 'test'
Dat

NameError: name 'data_path' is not defined

In [2]:
dataset_path = "~/fiftyone/coco-2017/validation/"
labels_path = "/home/sumbel/fiftyone/coco-2017/validation/labels.json"

In [3]:
convert_tensor = transforms.ToTensor()
convert_image = transforms.ToPILImage()

In [4]:
train_set = datasets.ImageFolder(root=dataset_path, transform=DataAugmentation())
train_loader = torch.utils.data.DataLoader(train_set, batch_size=2, shuffle=True)


In [5]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [6]:
device

device(type='cuda', index=0)

In [ ]:
class DenseCL(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.backbone = torch.nn.Sequential(*(list(torchvision.models.resnet50(pretrained=False).children())[:-1]))
        

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [9]:
x = train_set[0][0][0]

In [13]:
nn.Identity(x)

Identity()

In [18]:
model = torchvision.models.resnet50(pretrained=False)

In [17]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [19]:
newmodel = torch.nn.Sequential(*(list(model.children())[:-1]))
print(newmodel)

Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (4): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)


In [28]:
queue_g = torch.randn(2, 16)
queue_d = torch.randn(2, 16)
k_g = torch.randn(4, 2)
batch_size = k_g.shape[0]
ptr = 13
part_size =16 - ptr

In [29]:
part_size

3

In [33]:
queue_g

tensor([[-0.0972,  0.6202, -0.8769,  0.8696, -0.8465, -0.1367, -1.9609,  0.2901,
          0.8311,  0.1375,  0.3620,  1.1935,  0.3735, -2.6355, -0.2692,  0.8229],
        [ 1.7662,  0.5503, -0.9154,  0.2616,  0.2927,  0.3289, -0.7581,  0.8374,
          0.1419,  1.6457,  0.8342, -0.4118, -0.5598,  0.7100,  1.2096,  0.6213]])

In [22]:
queue_g[:, ptr: ptr + batch_size] = k_g.T

RuntimeError: The expanded size of the tensor (3) must match the existing size (4) at non-singleton dimension 1.  Target sizes: [2, 3].  Tensor sizes: [2, 4]

In [32]:
k_g.T[:, :part_size]

tensor([[-0.0894,  1.1810, -0.2993],
        [ 1.4787, -0.8195,  1.8449]])

In [31]:
queue_g[:, ptr:]

tensor([[-2.6355, -0.2692,  0.8229],
        [ 0.7100,  1.2096,  0.6213]])

In [34]:
k_g.T

tensor([[-0.0894,  1.1810, -0.2993,  0.5845],
        [ 1.4787, -0.8195,  1.8449, -1.1334]])

In [35]:
queue_g[:, ptr:] = k_g.T[:, :part_size]

In [39]:
queue_g[:, :batch_size - part_size] = k_g.T[:, part_size:]

In [36]:
k_g.T.shape

torch.Size([2, 4])

In [37]:
k_g.T[:, part_size:]

tensor([[ 0.5845],
        [-1.1334]])

In [38]:
queue_g[:, :batch_size - part_size]

tensor([[-0.0972],
        [ 1.7662]])